### ISSUE TITLE
Tracking issue for `Security process update`

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#178]
This is a tracking issue for `Security process update`, https://github.com/mimblewimble/grin-rfcs/pull/13

#### Steps:
* [x] Make updates and changes to `SECURITY.md` as per the RFC.
* [x] Move code reviews and audits section to a new page on the [wiki](https://github.com/mimblewimble/docs/wiki)
* [x] Move `chain splits` section into a new issue on `/grin`
* [x] Introduce canaries for each of the security contacts listed on `SECURITY.md`

#### Unresolved questions:

None so far

**Comment by lehnberg** [comment]
@j01tz feel free to pick this one up keep us up to date with your progress ✌️

**Comment by j01tz** [comment]
Thanks @lehnberg I'll begin working on implementing the RFC changes into `SECURITY.md` :+1:

**Comment by lehnberg** [comment]
> what do we really want to say here that isn't already in the standard?

I read it as a call to arms and encouragement for security researchers to contribute and do audits / review of our code on a voluntary basis. 

> Also not entirely sure which section of the wiki makes sense for this page, maybe Basics?

Perhaps under `Contributing`?

> Re: chain splits section:

What I meant there was to raise an issue for the aforementioned "chain split monitoring tool" so that it can be built or closed as a non-fix at some point. The rest does not need to be in an issue, I think.

**Comment by j01tz** [comment]
- Submitted a [PR for the RFC implementation](https://github.com/mimblewimble/grin/pull/3009)
- Added a [wiki page for code reviews and audits](https://github.com/mimblewimble/docs/wiki/Code-Reviews-and-Audits)
- Created an [issue for chain split monitoring tool](https://github.com/mimblewimble/grin/issues/3008)

**Comment by j01tz** [comment]
The remaining issues were addressed with https://github.com/mimblewimble/grin-security/pull/1. I think we can close this once the updated https://github.com/mimblewimble/grin/pull/3009 is merged.
