### ISSUE TITLE
Introduce conference sponsorship packages

### ISSUE THREAD

**Issue by lehnberg** [mimblewimble/grin-pm#8]
So far three packages have been discussed for sponsoring Grincon0. This process needs to be designed in detail. Feel free to raise suggestions and thoughts and brainstorm ideas in this thread.

# To-do
- [x] Agree on package names
- [x] Agree on package costs
- [x] Agree on package scarcity
- [x] Agree on what a sponsor receives at each level
- [x] Agree on the sponsorship application process made
- [ ] Define Sponsorship terms & conditions
- [x] Create sponsorship application webpage on grin-tech.org

# Details / Requirements

## Sponsorship application process
1. Webpage on Grin-tech.org.
1. Interested sponsor sends an application email to `tbd`.
1. Council reviews and approves/rejects application and communicates back to applicants.
1. Approved applicants receive an address to send their sponsorship fee to.
1. Upon receipt of funds, sponsor is considered accepted.

## Sponsorship packages
| | Silver | Gold | Grin |
|---|---|---|---|
|**Price (crypto equivalent)** | $3k | $15k | $30k |
| **Available packages** | 10 | 5 | 1 |
| **Package includes** | <ul><li>Silver-sized logo on grincon.org</ul> |<ul><li>Gold-sized logo on grincon.org <li>Logo on Grincon0 presentations</ul> |<ul><li>Grin-sized logo on grincon.org <li>Logo on Grincon0 presentations <li>Dinner with Grin council during Grincon0 <li>Logo (on the left arm) on the official Grincon0 t-shirt <li>Mention on the event email to meetup attendees</ul> |

**Total:** 10 * $3k + 5 * $15k + 1 * $30k = **$135k**

**Comment by lehnberg** [comment]
@catheryne see here for issue to track sponsorship packages

**Comment by 0xb100d** [comment]
For names I propose using the stages in alchemy for the creation of the philosopher's stone, way more unique:
1. nigredo, a blackening  - first (maybe problematic name?... can just use the other three tiers)
2. albedo, a whitening - secondary
3. citrinitas, a yellowing- penultimate
4. rubedo, a reddening - final

We can give everyone $50 gift cards or more to TMGOX, and for the lowest tier if we choose four it could just be a gift card and special stickers and a shirt or something.

**Comment by Catheryne** [comment]
With a little research on what various conferences are charging for sponsorships, it ranges. Top sponsorship levels: schools such as UC Berkeley charges $25k to be the title sponsor of their hackathon (get registration names for recruiting), NABitcoinConference top spot is $50k, Token Summit $30k for having the top sponsor's logo at the beginning of all video recordings, Consensus charges a whopping $150k - dang! At this juncture, I think we are probably closer to UCB. I would suggest maybe asking for $30k - 2 of them (registrant emails + logo on pressos&recordings + website logo placement), $20k - 5 (logos + website logo placement), $3k - (website logo). 

@0xb100d, I'm continuously amazed by your creativity! =) However, would recommend sticking to more conventional level naming for sponsors as proposed by @lehenberg (Silver, Gold, Grin) so there's no "deciphering" what the levels mean and are!

**Comment by lehnberg** [comment]
Okay so how does this look @Catheryne? I'm keen on the Grin package being scarce. @0xb100d I took the liberty to suggest you create Grincon0 shirts which we could place their logo on. Is the Gold package a bit "thin" at this stage perhaps? Dunno.

Other thoughts? @yeastplume @hashmap @ignopeverell etc?

**Comment by 0xb100d** [comment]
@lehnberg turnaround is going to be an issue, if we don't get sponsors soon we wont get t-shirts in time for grincon. We can always send them after the event, and also offer them on the shop, so that sponsors see that their logo'd shirts are still being showcased even if just online. I think a week is just about the shortest turnaround I can do. I'm not sure if a local printer could do better, but if that's what it comes down to I can send you designs. 

I haven't cross referenced who of the council is going to be at grincon0, is it almost everyone? because if that's the case we should get autographs on items there all at once.

It sounded like putting sponsors names into the TUI was a safe idea, after confirmation from people who matter most, I think only the top 6 packages at most should get the honor. I think that is going to draw a lot of interest. Also parchment-notes from Igno themselves could be in the packages. Unless we are going the full auction route for stuff like TUI and notes?

@Catheryne deciphering is half the fun. "My company was a Citrinitas sponsor of the first grin confenrence!" *everyone stares at them like some kind of wizard.* But I understand.

**Comment by Catheryne** [comment]
@lehnberg @0xb100d I think we should go with it now. Better earlier than later. Can @hashmap confirm whether we can do sponsorships for the venue and then send the email out ASAP?

**Comment by hashmap** [comment]
still waiting for cbase reply, will send one more email

**Comment by lehnberg** [comment]
https://github.com/mimblewimble/site/pull/15

**Comment by lehnberg** [comment]
https://grin-tech.org/grincon_sponsorship.html <- spread the word, and let's get some sponsors!

We have no proper terms & conditions for the sponsors, would be good to have something, so if anyone is feeling creative, please suggest something.

**Comment by 0xb100d** [comment]
We at least need to make it clear that there is no monetary/coin or insider information compensation for sponsorships in the conditions. Maybe also sponsors get first bids on future auctions (like having credits in the TUI).

**Comment by lehnberg** [comment]
Closing.
